name: Build
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Analysing the code with ruff
        run: |
          ruff check .

  GetVersion:
    runs-on: ubuntu-latest
    outputs:
      VersionNumber: ${{ steps.get_version_number.outputs.VersionNumber }}
      VersionNumberSpaceless: ${{ steps.get_version_number.outputs.VersionNumberSpaceless }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get version number
        id: get_version_number
        run: |
          python src/utils/readini.py\
              assets/Version.ini Release VersionNumber >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  BuildExecutableAndInstaller:
    runs-on: windows-latest
    needs: [GetVersion, Lint]
    env:
      VersionTag: v${{needs.GetVersion.outputs.VersionNumber}}
      VersionTagSpaceless: v${{needs.GetVersion.outputs.VersionNumberSpaceless}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Freeze Installer
        run: pyinstaller build-unsigned.spec
      - name: Build Installer
        run: iscc installer.iss

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist
          retention-days: 10

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Output
          retention-days: 10
