on:
  workflow_dispatch:
  push:
    branches:
      - master
      - inno6-installer
  pull_request:

jobs:
  build:
    runs-on: windows-latest      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build 
      run: |
        pyinstaller build-portable.spec
    - name: Build Installer
      run: |
         iscc installer.iss
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: 'Windows Release'
        path: '\a\project-gameface\project-gameface\Output\GameFace Installer.exe'
