on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Analysing the code with ruff
      run: |
        ruff check .

  set-variables:
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tag regex
      id: get-version
      run: |
        if [[ ${{ github.ref_name }} =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
        fi

  test-variable:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
    - name: Test variable
      run: |
        echo "version=${{needs.set-variables.outputs.version}}"
