on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types:
      - completed

jobs:

  # The guard job checks if the workflow_run event was successful and if the branch starts with 'refs/tags/v'.
  # If the conditions are met, it sets a flag indicating a match.
  guard:
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
        fi
    - name: guard
      if: steps.check-tag.outputs.match == 'true'
      run: |
        echo "Tag matches"

  variables:
    needs: [guard]
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tag regex
      id: get-version
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        fi

  # The build job runs on a Windows machine and performs various build steps.
  build:
    runs-on: windows-latest
    needs: [guard, variables]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Freeze Installer
      run: |
        pyinstaller build.spec 
    - name: Build Installer
      run: |
        iscc installer.iss
    - name: Freeze Portable
      run: |
        pyinstaller --distpath dist-portable build-portable.spec
    - name: Zip Portable 
      shell: pwsh
      run: |
        Copy-Item -Path assets -Destination dist-portable\ -Recurse
        Copy-Item -Path configs -Destination dist-portable\ -Recurse
        Compress-Archive -Path dist-portable -DestinationPath Grimassist-${{env.version}}-Portable.zip
    - name: rename installer
      run: |
        Move-Item -Path Output\GrimassistInstaller.exe -Destination Output\Grimassist-${{env.version}}-Installer.exe
    
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Output\Grimassist-${{env.version}}-Installer.exe
          Grimassist-${{env.version}}-Portable.zip
        tag_name: github.ref_name
        body: |
          Grimassist ${{env.version}}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}